# Generated by Django 4.1.1 on 2022-09-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='image',
        ),
        migrations.AddField(
            model_name='teams',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
