# Generated by Django 4.1.1 on 2022-09-22 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_remove_teams_image_teams_abbreviation_teams_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teams',
            old_name='name',
            new_name='teamName',
        ),
    ]
